default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  username: root
  password: '1234'

development: &development
  <<: *default
  database: hello_rails_development

test:
  <<: *default
  database: hello_rails_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
